export const SET_ACTIVE_CURRENCY = 'SET_ACTIVE_CURRENCY';
export const SET_CURRENCIES = 'SET_CURRENCY';
export const SET_LAST_PAGE = 'SET_LAST_PAGE';
export const ADD_HISTORY_ITEM = 'ADD_HISTORY_ITEM';
export const DELETE_HISTORY_ITEM = 'DELETE_HISTORY_ITEM';
